service: budget-14-prd

frameworkVersion: ">=1.1.0 <2.50.0"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: prd
  # environment:
  #   DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:429937773353:table/budget-14-dev"

functions:
  create:
    handler: todos/create.create
    events:
      - http:
          path: projects
          method: post
          cors: true

  list:
    handler: todos/list.list
    events:
      - http:
          path: projects
          method: get
          cors: false

  get:
    handler: todos/get.get
    events:
      - http:
          path: project_id/{project_id}/request_id/{request_id}
          method: get
          cors: false

  update:
    handler: todos/update.update
    events:
      - http:
          path: project_id/{project_id}/request_id/{request_id}
          method: put
          cors: true

  delete:
    handler: todos/delete.delete
    events:
      - http:
          path: project_id/{project_id}/request_id/{request_id}
          method: delete
          cors: false

  query:
    handler: todos/scan.scan
    events:
      - http:
          path: team/{team}/net_amount_remaining/{net_amount_remaining+}
          method: get
          cors: true

# resources:
#   Resources:
#     BudgetDynamoDbTable:
#       Type: 'AWS::DynamoDB::Table'
#       DeletionPolicy: Retain
#       Properties:
#         AttributeDefinitions:
#           -
#             AttributeName: project_id 
#             AttributeType: S
#         KeySchema:
#           -
#             AttributeName: project_id 
#             KeyType: HASH
#         ProvisionedThroughput:
#           ReadCapacityUnits: 1
#           WriteCapacityUnits: 1
#         TableName: ${self:provider.environment.DYNAMODB_TABLE}
